### ISSUE TITLE
Error during open of settings panel

### ISSUE THREAD

**Issue by wimsymons** [wimsymons/intellij-ppimport#3]
java.lang.NullPointerException
	at be.wimsymons.intellij.polopolyimport.ui.ConfigPanel.<init>(ConfigPanel.java:60)
	at be.wimsymons.intellij.polopolyimport.PPImportPlugin.createComponent(PPImportPlugin.java:118)
	at com.intellij.openapi.options.newEditor.OptionsEditor$Simple.<init>(OptionsEditor.java:1270)
	at com.intellij.openapi.options.newEditor.OptionsEditor.b(OptionsEditor.java:455)
	at com.intellij.openapi.options.newEditor.OptionsEditor.access$2500(OptionsEditor.java:68)
	at com.intellij.openapi.options.newEditor.OptionsEditor$9$1$1.run(OptionsEditor.java:424)
	at com.intellij.openapi.application.impl.ApplicationImpl.runEdtSafeAction(ApplicationImpl.java:1130)
	at com.intellij.openapi.options.newEditor.OptionsEditor$9$1.run(OptionsEditor.java:418)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:940)
	at com.intellij.openapi.options.newEditor.OptionsEditor$9.run(OptionsEditor.java:416)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:454)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
	at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:152)

**Comment by wimsymons** [comment]
Open too long. Closing for now
